---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: 
      package:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: tomcat
        state: present
    - name: add a tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    - name: download tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz"
        dest: /tmp/apache-tomcat-9.0.46.tar.gz
    - name: fetch the state
      stat:
        path: /opt/tomcat
      register: tomcat_download
    - name: unarchive the tar file
      unarchive:
        src: /tmp/apache-tomcat-9.0.46.tar.gz
        dest: /opt/tomcat
        extra_opts: [--strip-components=1]
      when: not tomcat_download.stat.exists
    - name: group permissions
      file:
        path: /opt/tomcat
        group: tomcat
        recurse: yes
    - name: owner permissions
      file:
        path: /opt/tomcat/conf/
        recurse: yes
        mode: g+r,g+x
    - name: ownership to webapp work tmp
      file: 
        path: "{{ item }}"
        owner: tomcat
        recurse: yes
      loop:
        - /opt/tomcat/webapps
        - /opt/tomcat/work
        - /opt/tomcat/temp
        - /opt/tomcat/logs
    - name: service file 
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: deamon reload and start
      systemd:
        name: tomcat
        daemon_reload: yes
        enabled: yes
        state: started
    - name: username and password
      copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/conf/tomcat-users.xml
      notify:
        - restating
    - name: context file
      copy:
        src: context.xml
        dest: "{{ item }}"
      loop:
        - /opt/tomcat/webapps/manager/META-INF/context.xml
        - /opt/tomcat/webapps/host-manager/META-INF/context.xml
  handlers: 
    - name: restating
      systemd:
        name: tomcat
        state: restarted
      


    