---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  vars: 
    tomcat_list:
     - /opt/tomcat/webapps
     - /opt/tomcat/works
     - /opt/tomcat/temp
     - /opt/tomcat/logs
  tasks:
    - name: 
      package:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: tomcat
        state: present
    - name: add a tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    - name: download tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz"
        dest: /tmp/apache-tomcat-9.0.46.tar.gz
    - name: unarchive the tar file
      unarchive:
        src: /tmp/apache-tomcat-9.0.46.tar.gz
        dest: /opt/tomcat
        extra_opts: [--strip-components=1]
    - name: group permissions
      file:
        path: /opt/tomcat
        group: tomcat
        recurse: yes
    - name: owner permissions
      file:
        path: /opt/tomcat/conf/
        recurse: yes
        mode: g+r,g+x
    - name: ownership to webapp work tmp
      file:
        path: "{{ tomcat_list }}"
        owner: tomcat
        recurse: yes
        

    