---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: 
      package:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: tomcat
        state: present
    - name: add a tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    