---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: 
      package:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: tomcat
        state: present
    - name: add a tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    - name: download tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.zip"
        dest: /tmp
    - name: unzip package
      package:
        name: unzip
        state: present
    - name: extracting file
      unarchive:
        src: /tmp/apache-tomcat-8.5.66.zip
        dest: /opt/tomcat/