---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  vars_files:
    - vars/packages.yaml
    - vars/password.yaml
  tasks:
    - name: 
      package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: "{{ groupname }}"
        state: present
    - name: add a tomcat user
      user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        shell: /bin/false
        home: "{{ tomcat_home }}"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_dest }}"
    - name: fetch the state
      stat:
        path: "{{ tomcat_home }}"
      register: tomcat_download
    - name: unarchive the tar file
      unarchive:
        src: "{{ tomcat_dest }}"
        dest: "{{ tomcat_home }}"
        extra_opts: [--strip-components=1]
      when: not tomcat_download.stat.exists
    - name: group permissions
      file:
        path: "{{ tomcat_home }}"
        group: "{{ groupname }}"
        owner: "{{ groupname }}"
        recurse: yes
        state: directory
    - name: owner permissions
      file:
        path: /opt/tomcat/conf/
        recurse: yes
        mode: u=rwx,g=rx
        state: directory
    - name: ownership to webapp work tmp
      file: 
        path: "{{ item }}"
        owner: tomcat
        recurse: yes
      loop: "{{ tomcat_ownership }}"
    - name: service file 
      copy:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify: 
        - reload daemon
    - name: deamon enabled and start
      systemd:
        name: "{{ username }}"
        enabled: yes
        state: started
    - name: username and password
      copy:
        src: tomcat-users.xml.j2
        dest: "{{ tomcat_user }}"
      notify:
        - restating
    - name: context file
      copy:
        src: context.xml
        dest: "{{ item }}"
      loop: "{{ tomcat_context }}"
      notify:
        - restating
  handlers:
    - name: reload daemon
      systemd:
        name: tomcat.service
        daemon_reload: yes
        state: started
    - name: restating
      systemd:
        name: tomcat
        state: restarted
      


    