---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: 
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: "{{ groupname }}"
        state: present
    - name: creat a tomcat home directory
      file:
        path: /opt/tomcat
        state: directory
    - name: add a tomcat user
      user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        home: "{{ tomcat_home }}"
        shell: /bin/false
    - name: download tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_dest }}"
    - name: fetch the state
      stat:
        path: "{{ tomcat_check_dir }}"
      register: tomcat_download
    - name: unarchive the tar file
      unarchive:
        src: "{{ tomcat_dest }}"
        dest: "{{ tomcat_home }}"
        extra_opts: [--strip-components=1]
      when: not tomcat_download.stat.exists
    - name: group permissions
      file:
        path: "{{ tomcat_home }}"
        group: "{{ groupname }}"
        owner: "{{ groupname }}"
        recurse: yes
        state: directory
    - name: owner permissions
      file:
        path: "{{ tomcat_check_dir }}"
        recurse: yes
        mode: u=rwx,g=rx
        state: directory
    - name: ownership to webapp work tmp
      file: 
        path: "{{ item }}"
        owner: tomcat
        group: tomcat
        recurse: yes
      loop: "{{ tomcat_ownership }}"
    - name: service file 
      copy:
        src: tomcat.service.j2
        dest: "{{ tomcat_servicefile }}"
      notify: 
        - reload daemon
    - name: deamon enabled and start
      service:
        name: tomcat.service
        enabled: yes
        state: started
    - name: username and password
      copy:
        src: tomcat-users.xml.j2
        dest: "{{ tomcat_user }}"
      notify:
        - restatring
    - name: context file
      copy:
        src: context.xml
        dest: "{{ item }}"
      loop: 
        - /opt/tomcat/webapps/manager/META-INF/context.xml
        - /opt/tomcat/webapps/host-manager/META-INF/context.xml
      notify:
        - restarting
  handlers:
    - name: reload daemon
      systemd:
        name: tomcat.service
        daemon_reload: yes
        state: started
    - name: restarting
      systemd:
        name: tomcat.service
        state: restarted
      


    