---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: 
      package:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: create a group
      group:
        name: tomcat
        state: present
    - name: add a tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    - name: download tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.zip"
        dest: /tmp
    - name: unzip package
      package:
        name: unzip
        state: present
    - name: extracting file
      unarchive:
        src: /tmp/apache-tomcat-8.5.66.zip
        dest: /opt/tomcat/
    - name: creating a link
      file:
        path: /opt/tomcat
        owner: tomcat
        recurse: yes
    - name: group read access
      file:
        path: "{{ item }}"
        mode: +x
      loop:
        - /opt/tomcat/apache-tomcat-8.5.66/bin/catalina-tasks.xml
        - /opt/tomcat/apache-tomcat-8.5.66/bin/bootstrap.jar
        - /opt/tomcat/apache-tomcat-8.5.66/bin/catalina.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/ciphers.bat  
        - /opt/tomcat/apache-tomcat-8.5.66/bin/ciphers.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/configtest.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/configtest.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/digest.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/setclasspath.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/shutdown.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/shutdown.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/startup.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/startup.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/version.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/version.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/daemon.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/digest.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/setclasspath.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/tool-wrapper.sh
        - /opt/tomcat/apache-tomcat-8.5.66/bin/tool-wrapper.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/catalina.bat
        - /opt/tomcat/apache-tomcat-8.5.66/bin/commons-daemon-native.tar.gz
        - /opt/tomcat/apache-tomcat-8.5.66/bin/commons-daemon.jar
        - /opt/tomcat/apache-tomcat-8.5.66/bin/tomcat-juli.jar
        - /opt/tomcat/apache-tomcat-8.5.66/bin/tomcat-native.tar.gz
    - name: permissions
      file:
        path: /opt/tomcat/apache-tomcat-8.5.66/conf/
        mode: g=r
        recurse: yes
    - name: conf permissions
      file: 
        path: /opt/tomcat/apache-tomcat-8.5.66/conf/
        mode: g=x



